apiVersion: v2
name: transip-ddns
description: Dynamic DNS updater for TransIP domains
type: application
version: 0.2.0
# renovate: datasource=packagist depName=transip/tipctl
appVersion: "6.34.2"
keywords:
  - ddns
  - dns
  - transip
  - dynamic-dns
home: https://github.com/transip/tipctl
sources:
  - https://github.com/transip/tipctl
maintainers:
  - name: jvhaarst
