{{- if and (not .Values.transip.privateKey.existingSecret) .Values.transip.privateKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transip-ddns.fullname" . }}-key
  labels:
    {{- include "transip-ddns.labels" . | nindent 4 }}
type: Opaque
data:
  transip.key: {{ .Values.transip.privateKey.value | b64enc }}
{{- end }}
